name: s3-copy ship action

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ci-ship-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        with:
          tagRegex: '(.*)'
          tagRegexGroup: 1

      - name: Create valid tag(s)
        id: tags
        run: |
          name="sarunask/s3-copy"
          output="$name:${{ steps.tagName.outputs.tag }},$name:latest"

          echo "::set-output name=all_tags::${output}"

      - name: Install latest major GO version
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Make build for ${{ steps.tags.outputs.all_tags }}
        run: |
          echo ${{ steps.tagName.outputs.tag }} > version.txt;
          make build

          find artifacts/ -type f -exec gzip -6 {} \;
          # send output multiline as env var: https://trstringer.com/github-actions-multiline-strings/
          echo "ARTIFACTS<<EOF" >> $GITHUB_ENV
          find artifacts -type f >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Release 2 Github
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          tag_name: ${{ steps.tagName.outputs.tag }}
          files: |
            ${{ env.ARTIFACTS }}
